add deployment verification

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,6 +46,17 @@ jobs:
       steps:
       - name: Lowercase the repo name and username
         run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+
+      - name: Check for Azure Secrets
+        run: |
+          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
+            echo "Error: AZURE_WEBAPP_PUBLISH_PROFILE is missing!"
+            exit 1
+          fi
+          if [ -z "${{ secrets.AZURE_WEBAPP_NAME }}" ]; then
+            echo "Error: AZURE_WEBAPP_NAME is missing!"
+            exit 1
+          fi
           
       - name: Deploy to Azure Web App
         id: deploy-to-webapp
